name: Publish Osharp Docs
on:
  push:
    branches: [master, dev/develop]

env:
  REGISTRY: docker.io
  IMAGE_NAME: gmf520/osharp.docs

jobs:
  publish_osharp_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Build Docker Image
      #   run: |
      #     cd ./docs
      #     docker build -t ${{env.IMAGE_NAME}}::latest .
      #     docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
      #     docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN_TOKEN }}
