name: Publish OSharp Docs

on:
  push:
    branches: [dev/develop]
  pull_request:
    branches: [master]

env:
  REGISTRY: docker.io
  IMAGE_NAME: gmf520/osharp.docs

jobs:
  publish_osharp_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CD Path
        run: |
          cd ./docs
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Publish Docker image
        id: build_and_publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ env.IMAGE_NAME }}:latest
