name: Publish OSharp Docs

on:
  push:
    branches: [dev/develop]
  pull_request:
    branches: [master]

jobs:
  publish_osharp_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
       name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          docker-login:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_LOGIN_TOKEN }}
      - name: Publish Docs
        run: |
          cd ./docs
          docker build -t gmf520/osharp-docs:${{steps.get_version.VERSION}} .
          docker tag gmf520/osharp-docs:${{steps.get_version.VERSION}} gmf520/osharp-docs:latest
          docker push gmf520/osharp-docs:${{steps.get_version.VERSION}}
          docker push gmf520/osharp-docs:latest
